Repository Mainkid/SisyphusGameEngine, pull requests merged in 2023-11, with the labels that each got.

#51 Flag Bitmasks
  GameEngine/Engine/GameEngine.cpp
  GameEngine/Engine/Tools/Data/FlagBitmask.h
  GameEngine/Engine/Tools/ErrorLogger.h
  GameEngine/GameEngine.vcxproj
  GameEngine/imgui.ini
Labels: Review Requested

#41 Log lifespan introduced
  .gitignore
  GameEngine/Engine/GameEngine.cpp
  GameEngine/Engine/Systems/EditorBillboardSystem.cpp
  GameEngine/Engine/Systems/EditorCameraSystem.cpp
  GameEngine/Engine/Systems/ErrorLoggingSystem.cpp
  GameEngine/Engine/Systems/ErrorLoggingSystem.h
  GameEngine/Engine/Systems/HardwareInitSystem.cpp
  GameEngine/Engine/Systems/InputSystem.cpp
  GameEngine/Engine/Systems/LightSystem.cpp
  GameEngine/Engine/Systems/MaterialUpdateSystem.cpp
  GameEngine/Engine/Systems/MeshSystem.cpp
  GameEngine/Engine/Systems/PhysicsSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudConsoleSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudContentBrowserSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudHierarchySystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudPostRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudPreRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudPropertiesSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudViewportSystem.cpp
  GameEngine/Engine/Systems/Rendering/ImageBasedLightingSystem.cpp
  GameEngine/Engine/Systems/Rendering/PostViewportRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/PreRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderInitSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/EditorBillboardRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/EditorGridRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/HbaoRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/LightRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/OpaqueRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/ShadowMapGenerationSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/ShadowRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/SkyboxRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/ToneMappingRenderSystem.cpp
  GameEngine/Engine/Systems/SkyboxSystem.cpp
  GameEngine/Engine/Systems/StartUpSystem.cpp
  GameEngine/Engine/Systems/TransformSystem.cpp
  GameEngine/imgui.ini
Labels: Done

#59 Physx features
  GameEngine/Engine/Components/ColliderComponent.cpp
  GameEngine/Engine/Components/ColliderComponent.h
  GameEngine/Engine/Components/MeshComponent.h
  GameEngine/Engine/Components/RBodyComponent.cpp
  GameEngine/Engine/Components/RBodyComponent.h
  GameEngine/Engine/Components/TransformComponent.h
  GameEngine/Engine/Core/ECS/SystemBase.h
  GameEngine/Engine/Core/EngineCore.cpp
  GameEngine/Engine/GameEngine.cpp
  GameEngine/Engine/Libs/x64/Debug/DirectXTK.pdb
  GameEngine/Engine/Libs/x64/Debug/GFSDK_SSAO_D3D11.win64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXCommon_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXCooking_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXExtensions_static_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXFoundation_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysX_64.lib
  GameEngine/Engine/Mono/Systems/MonoSyncSystem.cpp
  GameEngine/Engine/Scene/GameObjectHelper.cpp
  GameEngine/Engine/Scene/GameObjectHelper.h
  GameEngine/Engine/Systems/CollisionSystem.cpp
  GameEngine/Engine/Systems/CollisionSystem.h
  GameEngine/Engine/Systems/PhysicsSystem.cpp
  GameEngine/Engine/Systems/PhysicsSystem.h
  GameEngine/Engine/Systems/RBSystem.cpp
  GameEngine/Engine/Systems/RBSystem.h
  GameEngine/Engine/Systems/Rendering/HUD/HudConsoleSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudViewportSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/EditorBillboardRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/EditorGridRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/LightRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/OpaqueRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/ShadowMapGenerationSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/ShadowRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/ToneMappingRenderSystem.cpp
  GameEngine/Engine/Systems/ResourceService.h
  GameEngine/Engine/Systems/Systems.h
  GameEngine/Engine/Systems/TransformHelper.cpp
  GameEngine/Engine/Tools/Data/Vector.h
  GameEngine/Engine/Tools/MathHelper.h
  GameEngine/Game/Assets/Materials/Material0.mat
  GameEngine/Game/Assets/Materials/Material0.mat.meta
  GameEngine/GameEngine.vcxproj
  GameEngine/GameEngine.vcxproj.filters
  GameEngine/Physx.json
  GameEngine/imgui.ini
  TableData/Buttons.xlsx
  TableData/Dialogues — копия.xlsx
  TableData/Dialogues.xlsx
  TableData/DiaryEntries.xlsx
  TableData/Documents.xlsx
  TableData/Items.xlsx
  TableData/SceneObjects.xlsx
  TableData/Tasks.xlsx
  pre-build.bat
Labels: Review Requested

#62 physixs: runtime components control, run execution flow control, events
  GameEngine/Engine/Components/ColliderComponent.h
  GameEngine/Engine/Components/RBodyComponent.cpp
  GameEngine/Engine/Components/RBodyComponent.h
  GameEngine/Engine/Core/ECS/SystemBase.h
  GameEngine/Engine/Core/EngineCore.cpp
  GameEngine/Engine/GameEngine.cpp
  GameEngine/Engine/Scene/GameObjectHelper.cpp
  GameEngine/Engine/Scene/GameObjectHelper.h
  GameEngine/Engine/Systems/CollisionPreSystem.cpp
  GameEngine/Engine/Systems/CollisionPreSystem.h
  GameEngine/Engine/Systems/CollisionSystem.cpp
  GameEngine/Engine/Systems/PrepareEventsSystem.cpp
  GameEngine/Engine/Systems/RBSystem.cpp
  GameEngine/Engine/Systems/RBSystem.h
  GameEngine/Engine/Systems/Systems.h
  GameEngine/Engine/Tools/Data/Vector.cpp
  GameEngine/Engine/Tools/Data/Vector.h
  GameEngine/GameEngine.vcxproj
  GameEngine/GameEngine.vcxproj.filters
Labels: High Priority, Conflicts

#70 Debug render
  GameEngine/Engine/Assets/Shaders/EditorColliderShader.hlsl
  GameEngine/Engine/Components/ColliderComponent.cpp
  GameEngine/Engine/Components/ColliderComponent.h
  GameEngine/Engine/Components/RBodyComponent.cpp
  GameEngine/Engine/Components/RBodyComponent.h
  GameEngine/Engine/Core/DisplayWin32.cpp
  GameEngine/Engine/Core/EngineCore.cpp
  GameEngine/Engine/Core/Graphics/Buffer.cpp
  GameEngine/Engine/Core/Graphics/Buffer.h
  GameEngine/Engine/Events/SyHotReloadEvent.h
  GameEngine/Engine/Events/SyImageBasedLightingUpdateEvent.h
  GameEngine/Engine/Events/SyOnCreateColliderEvent.h
  GameEngine/Engine/Events/SyOnCreateRBodyEvent.h
  GameEngine/Engine/Events/SyPlayModeEndedEvent.h
  GameEngine/Engine/Events/SyPlayModeStartedEvent.h
  GameEngine/Engine/Events/SySceneLoadEvent.h
  GameEngine/Engine/GameEngine.cpp
  GameEngine/Engine/Libs/x64/Debug/DirectXTK.lib
  GameEngine/Engine/Libs/x64/Debug/DirectXTK.pdb
  GameEngine/Engine/Libs/x64/Debug/PhysXCommon_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXCooking_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXExtensions_static_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXFoundation_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysX_64.lib
  GameEngine/Engine/Libs/x64/Debug/fmodL.lib
  GameEngine/Engine/Libs/x64/Debug/fmodstudioL.lib
  GameEngine/Engine/Scene/GameObjectHelper.cpp
  GameEngine/Engine/Scene/GameObjectHelper.h
  GameEngine/Engine/Systems/CollisionPreSystem.cpp
  GameEngine/Engine/Systems/CollisionSystem.cpp
  GameEngine/Engine/Systems/EngineContext.h
  GameEngine/Engine/Systems/ErrorLoggingSystem.cpp
  GameEngine/Engine/Systems/RBSystem.cpp
  GameEngine/Engine/Systems/RBSystem.h
  GameEngine/Engine/Systems/Rendering/HUD/HudPropertiesSystem.cpp
  GameEngine/Engine/Systems/Rendering/HUD/HudViewportSystem.cpp
  GameEngine/Engine/Systems/Rendering/ImageBasedLightingSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderContext.h
  GameEngine/Engine/Systems/Rendering/RenderInitSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/EditorColliderRenderSystem.cpp
  GameEngine/Engine/Systems/Rendering/RenderPipeline/EditorColliderRenderSystem.h
  GameEngine/Engine/Systems/ResourceService.cpp
  GameEngine/Engine/Systems/SkyboxSystem.cpp
  GameEngine/Engine/Systems/Systems.h
  GameEngine/Engine/Systems/TransformSystem.cpp
  GameEngine/Engine/Tools/Data/FlagBitmask.h
  GameEngine/Engine/Tools/Data/Geometry.h
  GameEngine/Engine/Tools/Data/Vector.h
  GameEngine/Engine/Tools/ErrorLogger.h
  GameEngine/Engine/Tools/MathHelper.h
  GameEngine/GameEngine.vcxproj
  GameEngine/GameEngine.vcxproj.filters
  GameEngine/imgui.ini
  Temp.txt
Labels: WIP

#69 Наконец-то добавлены глобальные трансформы
  GameEngine/Engine/Components/TransformComponent.h
  GameEngine/Engine/Core/Tools/ImageLoader.cpp
  GameEngine/Engine/Core/Tools/Structures/Vector.h
  GameEngine/Engine/Features/ErrorLogging/Systems/ErrorLoggingSystem.h
  GameEngine/Engine/Features/Particles/Systems/ParticlesSystem.cpp
  GameEngine/Engine/Features/Particles/Systems/ParticlesSystem.h
  GameEngine/Engine/Features/Physics/Systems/RBSystem.cpp
  GameEngine/Engine/Features/Rendering/RenderPipeline/LightRenderSystem.cpp
  GameEngine/Engine/Features/Resources/Systems/ResourceSystem.cpp
  GameEngine/Engine/Features/Resources/Systems/ResourceSystem.h
  GameEngine/Engine/GameEngine.cpp
  GameEngine/Engine/Libs/x64/Debug/PhysXCommon_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXCooking_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXExtensions_static_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXFoundation_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXVehicle2_static_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysXVehicle_static_64.lib
  GameEngine/Engine/Libs/x64/Debug/PhysX_64.lib
  GameEngine/Engine/Scene/GameObjectHelper.cpp
  GameEngine/Engine/Systems/EditorCameraSystem.cpp
  GameEngine/Engine/Systems/TransformHelper.cpp
  GameEngine/Engine/Systems/TransformHelper.h
  GameEngine/Engine/Systems/TransformSystem.cpp
  GameEngine/Game/Assets/Materials/Pillar
  GameEngine/imgui.ini
Labels: Done
